# Generated by Django 2.1.7 on 2019-04-16 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentmedia',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_uploads', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='developmentmedia',
            name='development',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_media', to='developments.Development'),
        ),
        migrations.AddField(
            model_name='development',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
