# Generated by Django 2.1.7 on 2019-02-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='CSUS Email')),
                ('account_type', models.CharField(choices=[('ST', 'Student'), ('TA', 'Teaching Assistant'), ('FA', 'Faculty')], default='ST', max_length=2, verbose_name='Account Type')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('middle_initial', models.CharField(blank=True, max_length=1, verbose_name='MI')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
