# Generated by Django 2.1.7 on 2019-03-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190301_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='middle_initial',
        ),
    ]
