# Generated by Django 2.1.7 on 2019-02-24 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('article_type', models.CharField(choices=[('RD', 'Raw Data'), ('AD', 'Analyzed Data'), ('RE', 'Report'), ('PO', 'Poster'), ('OT', 'Other')], max_length=2)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('discipline', models.CharField(choices=[('CY', 'Chemistry'), ('BY', 'Biology'), ('CE', 'Civil Engineering')], max_length=2)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_media', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='articles.Article')),
            ],
        ),
    ]
