# Generated by Django 2.1.7 on 2019-03-09 17:16

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Type a description...', max_length=512, verbose_name='description')),
                ('subject', models.CharField(blank=True, choices=[('BI', 'Biology'), ('CH', 'Chemistry'), ('CE', 'Civil Engineering'), ('EN', 'Environmental Studies'), ('GE', 'Geology')], max_length=2, verbose_name='subject')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('section', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('semester', models.CharField(blank=True, choices=[('', '---------'), ('FA', 'Fall'), ('WI', 'Winter'), ('SP', 'Spring'), ('SU', 'Summer')], default='FA', max_length=2, verbose_name='semester')),
                ('year', models.PositiveSmallIntegerField(blank=True, choices=[('', '---------'), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000)], default=articles.models.Article.current_year, null=True, verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_media', models.FileField(upload_to=articles.models.ArticleMedia.upload_to, verbose_name='file upload')),
                ('article_type', models.CharField(choices=[('', '---------'), ('AD', 'Analyzed Data'), ('PO', 'Poster'), ('RD', 'Raw Data'), ('RE', 'Report'), ('OT', 'Other')], help_text='Select the file type', max_length=2, verbose_name='article type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='articles.Article')),
            ],
        ),
    ]
