# Generated by Django 2.1.7 on 2019-02-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_name',
            field=models.CharField(default='filename', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
