# Generated by Django 2.1.7 on 2019-02-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190216_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
