# Generated by Django 2.1.7 on 2019-02-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190222_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemedia',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='articles.Article'),
        ),
    ]
