# Generated by Django 2.1.7 on 2019-02-17 05:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190216_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='uploads/%Y/%m/%d'), default=list, size=None),
        ),
    ]
