# Generated by Django 2.1.7 on 2019-04-29 02:26

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension



class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0002_auto_20190428_1924'),
    ]

    operations = [
        TrigramExtension(),
    ]
