# Generated by Django 2.1.7 on 2019-04-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0002_auto_20190420_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomemedia',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
